"""empty message

Revision ID: 63a208ba6fa9
Revises: 81044d80d07c
Create Date: 2026-05-29 09:53:29.641230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a208ba6fa9'
down_revision = '81044d80d07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personaje_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'personajes', ['personaje_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('personaje_id')

    # ### end Alembic commands ###
