"""empty message

Revision ID: 81044d80d07c
Revises: ff14c5ffcfd6
Create Date: 2026-05-29 09:38:00.294189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81044d80d07c'
down_revision = 'ff14c5ffcfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes')
    # ### end Alembic commands ###
